name: Build and Release

on:
  push:
    tags:
      - 'v2.0.2'  # 例: v2.0.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Upload JAR
        uses: actions/upload-artifact@v3
        with:
          name: plugin-jar
          path: build/libs/*-all.jar

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: plugin-jar

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: "*.jar"